package lexical

const L_SELECT = "select"
const L_DISTINCT = "distinct"
const L_FROM = "from"
const L_WHERE = "where"
const L_ORDER = "order"
const L_BY = "by"
const L_OR = "or"
const L_AND = "and"
const L_LIMIT = "limit"
const L_IN = "in"
const L_ASC = "asc"
const L_DESC = "desc"
const L_LIKE = "like"
const L_NOT = "not"
const L_COUNT = "count"
const L_SHOW = "show"
const L_TABLES = "tables"
const L_DATABASES = "databases"
